github: [user1, user2, user3, user4]  # Replace with up to 4 GitHub Sponsors-enabled usernames
patreon: patreon_user  # Replace with a single Patreon username
open_collective: open_collective_user  # Replace with a single Open Collective username
ko_fi: ko_fi_user  # Replace with a single Ko-fi username
tidelift: npm/babel  # Replace with a single Tidelift package or platform name
community_bridge: cloud-foundry  # Replace with a single Community Bridge project name
liberapay: liberapay_user  # Replace with a single Liberapay username
issuehunt: issuehunt_user  # Replace with a single IssueHunt username
lfx_crowdfunding: cloud-foundry  # Replace with a single LFX Crowdfunding project name
polar: polar_user  # Replace with a single Polar username
buy_me_a_coffee: buymeacoffee_user  # Replace with a single Buy Me a Coffee username
thanks_dev: thanks_dev_user  # Replace with a single thanks.dev username
custom: ['https://customlink1.com', 'https://customlink2.com']  # Replace with up to 4 custom sponsorship URLs

